### PR TITLE
Fix the build for Linux ARM64

### PR DESCRIPTION
**Pull request by julien-faye**
Pass '-mcx16' as a CMake option only for x86_64.
Run the build and tests in a Docker container for ARM64. Do not use sanitizers because they are not usable without ptrace (in container).

### CODE REVIEW

**Comment by ekg** [comment]
First, it's awesome. Second, I'm not sure that `-mcx16` is still a requirement for any build, on newer systems. Anyone have any insight?

I need to test before merging, but it looks good.

**Comment by martin-g** [comment]
Good job, @julien-faye !
I just needed to build Seqwish on Linux ARM64 and your PR helped me to do it quickly!
I hope it get merged soon!

**Comment by ekg** [comment]
Just did some quick tests and this looks good to go! Thank you!

**Comment by ekg** [comment]
Unfortunately, I now can't build (apparently due to the drop of the compare and swap compiler option):

```
transclosure.cpp:(.text+0x1051): undefined reference to `__sync_bool_compare_and_swap_16'
```

How should we resolve this?

**Comment by ekg** [comment]
Weirdly, I can build on one system, but not another. On both, I'm using GCC 11 and have x86_64. On one I'm building in guix.

**Comment by ekg** [comment]
It looks like the problem was with guix! So no issues here.

**Pull request merged**
