### PR TITLE
Still generic on aarch64

### PR DESCRIPTION
**Pull request by AndreaGuarracino**

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
@julien-faye, @martin-g, could you please check if you are able to build such a branch with your Linux ARM64 systems?

**Comment by martin-g** [comment]
I guess it won't work but I will be able to say for sure at Wednesday.
The current CI check on aarch64 passes because it uses Release mode.

**Comment by AndreaGuarracino** [comment]
`-march=haswell` allows us to compile `seqwish` in `Generic` mode (that is, without `-march=native`, which is too bounded to the system where the tool is compiled) when building the `Docker` image of `pggb` (https://github.com/pangenome/pggb/blob/master/Dockerfile#L60). I wonder if such `pggb`'s `Docker` images would run on your systems.

For now, we go this way, hoping for more general solutions in the future. Thank you very much for your feedback!

**Comment by martin-g** [comment]
@AndreaGuarracino I will propose a PR where `haswell` will be set as a default but the user could override it with `cmake -D...`. Coming in few minutes!

**Pull request merged**
